[manager]
ratio = [2, 4, 4]
sort_by = "natural"
sort_dir_first = true
sort_translit = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true

[preview]
wrap = "yes"
tab_size = 4

[opener]
vs_code = [{ run = 'code "$@"', block = true, for = "unix" }]
default_editor = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[open]
append_rules = [{ name = "*", use = "default_editor" }]
rules = [{ name = "*.md", use = ["vs_code", "default_editor"] }]
